### ISSUE TITLE
Command error

### ISSUE THREAD

**Issue by chicuong2412** [WinfXK/Breast#1]
When I write / bre or whatever command I have edited in Command.yml, nothing happens.
And you should make a tutorial so that everyone can use the plugin effectively.

**Comment by WinfXK** [comment]
Ok, I will make the tutorial after I perfect it. Besides, I am sorry to reply to you so late, I have been a little busy recently




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miner123a"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 晚上6:52
收件人:&nbsp;"WinfXK/Breast"<Breast@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[WinfXK/Breast] Command error (#1)





 
When I write / bre or whatever command I have edited in Command.yml, nothing happens.
 And you should make a tutorial so that everyone can use the plugin effectively.

**Comment by chicuong2412** [comment]
when i run plugin, it throw
Enabling Breast v1.0-alpha
> java.io.FileNotFoundException: C:\Users\Administrator\Desktop\New%20folder\plugins\Breast_v1.0.alpha.jar (The system cannot find the path specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at cn.winfxk.breast.ResCheck.start(ResCheck.java:130)
        at cn.winfxk.breast.Activate.<init>(Activate.java:72)
        at cn.winfxk.breast.Breast.onEnable(Breast.java:28)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
        at cn.nukkit.Server.enablePlugin(Server.java:741)
        at cn.nukkit.Server.enablePlugins(Server.java:730)
        at cn.nukkit.Server.<init>(Server.java:566)
        at cn.nukkit.Nukkit.main(Nukkit.java:112)
and i can't use the command in the file command.yml

**Comment by WinfXK** [comment]
I'm sorry, I'll deal with it as soon as possible!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miner123a"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 下午3:42
收件人:&nbsp;"WinfXK/Breast"<Breast@noreply.github.com&gt;;
抄送:&nbsp;"冰月"<Winfxk@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [WinfXK/Breast] Command error (#1)





 
when i run plugin, it throw
 Enabling Breast v1.0-alpha
  
java.io.FileNotFoundException: C:\Users\Administrator\Desktop\New%20folder\plugins\Breast_v1.0.alpha.jar (The system cannot find the path specified)
 at java.util.zip.ZipFile.open(Native Method)
 at java.util.zip.ZipFile.(Unknown Source)
 at java.util.zip.ZipFile.(Unknown Source)
 at java.util.jar.JarFile.(Unknown Source)
 at java.util.jar.JarFile.(Unknown Source)
 at cn.winfxk.breast.ResCheck.start(ResCheck.java:130)
 at cn.winfxk.breast.Activate.(Activate.java:72)
 at cn.winfxk.breast.Breast.onEnable(Breast.java:28)
 at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
 at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
 at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
 at cn.nukkit.Server.enablePlugin(Server.java:741)
 at cn.nukkit.Server.enablePlugins(Server.java:730)
 at cn.nukkit.Server.(Server.java:566)
 at cn.nukkit.Nukkit.main(Nukkit.java:112)
 and i can't use the command in the file command.yml

**Comment by WinfXK** [comment]
Hey brothers

I have updated the Breast!

You can find it in the [https://github.com/WinfXK/Breast/releases/tag/v1.0-beta],

I have fixed all the errors you submitted to me, and I have updated the use of the command,

I will complete other functions as soon as possible,



By the way, what version of Java do you use?








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miner123a"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 下午3:42
收件人:&nbsp;"WinfXK/Breast"<Breast@noreply.github.com&gt;;
抄送:&nbsp;"冰月"<Winfxk@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [WinfXK/Breast] Command error (#1)





 
when i run plugin, it throw
 Enabling Breast v1.0-alpha
  
java.io.FileNotFoundException: C:\Users\Administrator\Desktop\New%20folder\plugins\Breast_v1.0.alpha.jar (The system cannot find the path specified)
 at java.util.zip.ZipFile.open(Native Method)
 at java.util.zip.ZipFile.(Unknown Source)
 at java.util.zip.ZipFile.(Unknown Source)
 at java.util.jar.JarFile.(Unknown Source)
 at java.util.jar.JarFile.(Unknown Source)
 at cn.winfxk.breast.ResCheck.start(ResCheck.java:130)
 at cn.winfxk.breast.Activate.(Activate.java:72)
 at cn.winfxk.breast.Breast.onEnable(Breast.java:28)
 at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
 at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
 at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
 at cn.nukkit.Server.enablePlugin(Server.java:741)
 at cn.nukkit.Server.enablePlugins(Server.java:730)
 at cn.nukkit.Server.(Server.java:566)
 at cn.nukkit.Nukkit.main(Nukkit.java:112)
 and i can't use the command in the file command.yml

**Comment by chicuong2412** [comment]
> Hey brothers I have updated the Breast! You can find it in the [https://github.com/WinfXK/Breast/releases/tag/v1.0-beta], I have fixed all the errors you submitted to me, and I have updated the use of the command, I will complete other functions as soon as possible, By the way, what version of Java do you use?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"miner123a"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月18日(星期一) 下午3:42 收件人:&nbsp;"WinfXK/Breast"<Breast@noreply.github.com&gt;; 抄送:&nbsp;"冰月"<Winfxk@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [WinfXK/Breast] Command error (#1) when i run plugin, it throw Enabling Breast v1.0-alpha java.io.FileNotFoundException: C:\Users\Administrator\Desktop\New%20folder\plugins\Breast_v1.0.alpha.jar (The system cannot find the path specified) at java.util.zip.ZipFile.open(Native Method) at java.util.zip.ZipFile.(Unknown Source) at java.util.zip.ZipFile.(Unknown Source) at java.util.jar.JarFile.(Unknown Source) at java.util.jar.JarFile.(Unknown Source) at cn.winfxk.breast.ResCheck.start(ResCheck.java:130) at cn.winfxk.breast.Activate.(Activate.java:72) at cn.winfxk.breast.Breast.onEnable(Breast.java:28) at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) at cn.nukkit.Server.enablePlugin(Server.java:741) at cn.nukkit.Server.enablePlugins(Server.java:730) at cn.nukkit.Server.(Server.java:566) at cn.nukkit.Nukkit.main(Nukkit.java:112) and i can't use the command in the file command.yml — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I using the newest version of Java

**Comment by WinfXK** [comment]
Ok, you can try to see if there are any new bugs. I will finish the other functions as soon as possible




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miner123a"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 中午12:53
收件人:&nbsp;"WinfXK/Breast"<Breast@noreply.github.com&gt;;
抄送:&nbsp;"冰月"<Winfxk@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [WinfXK/Breast] Command error (#1)





  
Hey brothers I have updated the Breast! You can find it in the [https://github.com/WinfXK/Breast/releases/tag/v1.0-beta], I have fixed all the errors you submitted to me, and I have updated the use of the command, I will complete other functions as soon as possible, By the way, what version of Java do you use?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"miner123a"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月18日(星期一) 下午3:42 收件人:&nbsp;"WinfXK/Breast"<Breast@noreply.github.com&gt;; 抄送:&nbsp;"冰月"<Winfxk@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [WinfXK/Breast] Command error (#1) when i run plugin, it throw Enabling Breast v1.0-alpha java.io.FileNotFoundException: C:\Users\Administrator\Desktop\New%20folder\plugins\Breast_v1.0.alpha.jar (The system cannot find the path specified) at java.util.zip.ZipFile.open(Native Method) at java.util.zip.ZipFile.(Unknown Source) at java.util.zip.ZipFile.(Unknown Source) at java.util.jar.JarFile.(Unknown Source) at java.util.jar.JarFile.(Unknown Source) at cn.winfxk.breast.ResCheck.start(ResCheck.java:130) at cn.winfxk.breast.Activate.(Activate.java:72) at cn.winfxk.breast.Breast.onEnable(Breast.java:28) at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) at cn.nukkit.Server.enablePlugin(Server.java:741) at cn.nukkit.Server.enablePlugins(Server.java:730) at cn.nukkit.Server.(Server.java:566) at cn.nukkit.Nukkit.main(Nukkit.java:112) and i can't use the command in the file command.yml — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
I using the newest version of Java

**Comment by chicuong2412** [comment]
Ok i will close the issue.
If i were find a new issue, i would create a new issue

**Comment by chicuong2412** [comment]
When i use command as player, it throw
Unhandled exception executing command "bre main" in breast: java.lang.NullPointerException
        at cn.winfxk.breast.form.FormBase.<init>(FormBase.java:51)
        at cn.winfxk.breast.form.MainForm.<init>(MainForm.java:29)
        at cn.winfxk.breast.cmd.MyCommand.execute(MyCommand.java:159)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)
        at cn.nukkit.Server.dispatchCommand(Server.java:759)
        at me.xxsirgamesxx.cmdas.Main.onCommand(Main.java:75)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)
        at cn.nukkit.Server.dispatchCommand(Server.java:759)
        at cn.nukkit.console.NukkitConsole.lambda$runCommand$0(NukkitConsole.java:35)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277)
        at cn.nukkit.Server.tick(Server.java:1140)
        at cn.nukkit.Server.tickProcessor(Server.java:911)
        at cn.nukkit.Server.start(Server.java:888)
        at cn.nukkit.Server.<init>(Server.java:573)
        at cn.nukkit.Nukkit.main(Nukkit.java:112)

17:28:37 [ERROR] Throwing
java.lang.NullPointerException: null
        at cn.winfxk.breast.form.FormBase.<init>(FormBase.java:51) ~[?:?]
        at cn.winfxk.breast.form.MainForm.<init>(MainForm.java:29) ~[?:?]
        at cn.winfxk.breast.cmd.MyCommand.execute(MyCommand.java:159) ~[?:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:759) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at me.xxsirgamesxx.cmdas.Main.onCommand(Main.java:75) ~[?:?]
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:759) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.console.NukkitConsole.lambda$runCommand$0(NukkitConsole.java:35) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1140) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:911) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:888) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:573) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]

**Comment by WinfXK** [comment]
OK！I will deal with it as soon as possible. Please wait






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miner123a"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 晚上6:35
收件人:&nbsp;"WinfXK/Breast"<Breast@noreply.github.com&gt;;
抄送:&nbsp;"冰月"<Winfxk@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [WinfXK/Breast] Command error (#1)





 
When i use command as player, it throw
 Unhandled exception executing command "bre main" in breast: java.lang.NullPointerException
 at cn.winfxk.breast.form.FormBase.(FormBase.java:51)
 at cn.winfxk.breast.form.MainForm.(MainForm.java:29)
 at cn.winfxk.breast.cmd.MyCommand.execute(MyCommand.java:159)
 at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)
 at cn.nukkit.Server.dispatchCommand(Server.java:759)
 at me.xxsirgamesxx.cmdas.Main.onCommand(Main.java:75)
 at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
 at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257)
 at cn.nukkit.Server.dispatchCommand(Server.java:759)
 at cn.nukkit.console.NukkitConsole.lambda$runCommand$0(NukkitConsole.java:35)
 at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
 at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296)
 at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277)
 at cn.nukkit.Server.tick(Server.java:1140)
 at cn.nukkit.Server.tickProcessor(Server.java:911)
 at cn.nukkit.Server.start(Server.java:888)
 at cn.nukkit.Server.(Server.java:573)
 at cn.nukkit.Nukkit.main(Nukkit.java:112)
 
17:28:37 [ERROR] Throwing
 java.lang.NullPointerException: null
 at cn.winfxk.breast.form.FormBase.(FormBase.java:51) ~[?:?]
 at cn.winfxk.breast.form.MainForm.(MainForm.java:29) ~[?:?]
 at cn.winfxk.breast.cmd.MyCommand.execute(MyCommand.java:159) ~[?:?]
 at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.Server.dispatchCommand(Server.java:759) ~[nukkit-1.0-SNAPSHOT.jar:?]
 at me.xxsirgamesxx.cmdas.Main.onCommand(Main.java:75) ~[?:?]
 at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33) ~[nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) ~[nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.Server.dispatchCommand(Server.java:759) ~[nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.console.NukkitConsole.lambda$runCommand$0(NukkitConsole.java:35) ~[nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.Server.tick(Server.java:1140) [nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.Server.tickProcessor(Server.java:911) [nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.Server.start(Server.java:888) [nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.Server.(Server.java:573) [nukkit-1.0-SNAPSHOT.jar:?]
 at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]

**Comment by WinfXK** [comment]
Hey brother,
I'm sorry to bother you with a buggy plugin,
This is the new version, you can test it out and fix the problem you mentioned (missing one "!"brings mistakes...)
I also updated the plugin administrator Settings and configuration Settings
https://github.com/WinfXK/Breast/releases/tag/v1.0-Gamma

**Comment by chicuong2412** [comment]
when i using Item editer, it throw:
java.lang.ClassCastException: cn.nukkit.form.response.FormResponseCustom cannot be cast to cn.nukkit.form.response.FormResponseSimple
        at cn.winfxk.breast.form.FormBase.getSimple(FormBase.java:200)
        at cn.winfxk.breast.form.more.sett.NBTEditor.disMain(NBTEditor.java:56)
        at cn.winfxk.breast.Breast.onFormResponded(Breast.java:99)
        at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546)
        at cn.nukkit.Player.handleDataPacket(Player.java:2596)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:197)
        at cn.nukkit.network.Network.processBatch(Network.java:180)
        at cn.nukkit.Player.handleDataPacket(Player.java:2102)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:83)
        at cn.nukkit.Server.tick(Server.java:1132)
        at cn.nukkit.Server.tickProcessor(Server.java:911)
        at cn.nukkit.Server.start(Server.java:888)
        at cn.nukkit.Server.<init>(Server.java:573)
        at cn.nukkit.Nukkit.main(Nukkit.java:112)

**Comment by chicuong2412** [comment]
This plugin supports admin creating an exchange between 2 items with NBT.
For example:
Item1 (with name, lore, enchant) is used to exchange for Item2 (with name, lore, enchant).
If Item1 does not meet the set requirements, it will not be possible to exchange.

**Comment by WinfXK** [comment]
Sorry for the inconvenience, I will fix it as soon as possible

**Comment by chicuong2412** [comment]
> This plugin supports admin creating an exchange between 2 items with NBT.
> For example:
> Item1 (with name, lore, enchant) is used to exchange for Item2 (with name, lore, enchant).
> If Item1 does not meet the set requirements, it will not be possible to exchange.

Breast have this feature ???

**Comment by WinfXK** [comment]
It compares whether two items are the same (including ID, Damage, NBT, enchant, etc.), but not the name

**Comment by chicuong2412** [comment]
That still awesome, i will wait for a tutorial

**Comment by WinfXK** [comment]
I'm changing the way the ItemList page is displayed, and showing all the items (hundreds) will get stuck

**Comment by chicuong2412** [comment]
and how to create the trade for tow item, i only see EconomyAPI

**Comment by WinfXK** [comment]
Using items to trade items?

**Comment by chicuong2412** [comment]
yes

**Comment by WinfXK** [comment]
You can look at "real-time trading"

**Comment by chicuong2412** [comment]
ok thanks, i have to go now, see you later

**Comment by WinfXK** [comment]
best wishes to you

**Comment by WinfXK** [comment]
A new version has been released！
Link:   https://github.com/WinfXK/Breast/releases/tag/v1.0.delte
I also fixed some bugs that I found myself,
I found a lot of bugs...
------------------------------------------------
Fixed all known problems in Gamma
Fixed NBT export error
Optimize the player's judgment mode to solve the problem that no player can trade
Optimize item support list display mode to prevent lag
Optimize item transaction retrieval method to prevent item loss
Added interface error handling to prevent players from losing items when the transaction fails

**Comment by chicuong2412** [comment]
Dude, can I make an endless deal, players can exchange for the item I ordered in advance if eligible for at any time, it's like creating a shop, but here is not buying with money but with 1 item

**Comment by WinfXK** [comment]
I'm sorry I didn't quite catch your drift

**Comment by chicuong2412** [comment]
it mean, a shop for player can buy a item, but using item as a item for trade.

**Comment by WinfXK** [comment]
At present, it can only be used for real-time transaction, but I will update the items in the store with the items in the later stage


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miner123a"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 下午2:03
收件人:&nbsp;"WinfXK/Breast"<Breast@noreply.github.com&gt;;
抄送:&nbsp;"冰月"<Winfxk@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [WinfXK/Breast] Command error (#1)





 
it mean, a shop for player can buy a item, but using item as a item for trade.

**Comment by chicuong2412** [comment]
are you working on the new version?

**Comment by WinfXK** [comment]
It is currently being developed primarily for Knickers






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miner123a"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 晚上10:01
收件人:&nbsp;"WinfXK/Breast"<Breast@noreply.github.com&gt;;
抄送:&nbsp;"冰月"<Winfxk@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [WinfXK/Breast] Command error (#1)





 
are you working on the new version?

**Comment by chicuong2412** [comment]
I will waiting for a new update about trade items as a shop

**Comment by WinfXK** [comment]
Ok, I'll give priority to updating the store






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"miner123a"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月24日(星期天) 中午11:57
收件人:&nbsp;"WinfXK/Breast"<Breast@noreply.github.com&gt;;
抄送:&nbsp;"冰月"<Winfxk@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [WinfXK/Breast] Command error (#1)





 
I will waiting for a new update about trade items as a shop
